---
# vars file for cisco

#
# vLAN parameters
#
vlans_list:
  - name: vUser
    id: 100
  - name: vVoIP
    id: 200
  - name: Security
    id: 300
  - name: MGMT
    id: 900

#
# SNMP Configuration
#
snmp_config_dict:
  communities:
    - name: pub
      rw: true
    - name: priv
      rw: true
  contact: My Lovely IT
  location: "{{ site_name ~ ( ('/' ~ location) if location is defined ) }}"

#
# ACL
#
acl_config_global:
  - name: Access-SNMP
    acls:
      - name: 172.17.0.1
        log: true
      - name: 172.17.0.2
  - name: Access-NTP
    acls:
      - name: 172.17.0.3
  - name: Access-VTY
    type: extended
    acls:
      - name: 172.17.0.98
      - name: 172.17.0.0
        wildcard: 0.0.0.255
      - name: any
        grant: deny
        log: true
