---
# vars file for spine-leaf

#
# NTP Server
#
ntp_server_list:
  - name: 172.10.0.5
    prefer: true
    source: vlan 900
  - name: 172.10.0.6
    prefer: false
    source: vlan 900

dns_server_list:
  - 8.8.8.8

#
# Site Id
#
site_id: 1
site_name: Amsterdam/Building1

#
# Local ACLs
#
acl_config_local:
  - name: Access-Local
    acls:
      - name: 10.10.10.10
