---
# tasks file for cisco

#
# Stop if Startup and Running does not match
#

#
# Checking if running != startup
#

- name: Reading Running-Config
  cisco.ios.ios_config:
    diff_against: startup
  register: output

- name: Failing if config are different (require --diff)
  fail:
    msg: Configuration are not saved
  when: output.changed

#
# Include vars for the current site
#
- name: Include vars for the current switch
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "site_{{ site }}.yml"
        - "site_default.yml"

#
# Setting facts for Ciscos
#
- name: Setting Facts
  ansible.builtin.include_tasks: set_facts.yml
  register: output

#
# Setting global configuration
#
- name: Setting Global Configuration
  ansible.builtin.include_tasks: set_global_conf.yml
  register: output

#
# Setting vLANs
#
- name: Setting vLans
  ansible.builtin.include_tasks: set_vlans.yml
  register: output

#
# Setting STP
#
- name: Setting Spanning-Tree Protocol
  ansible.builtin.include_tasks: set_stp.yml
  register: output

#
# Set ACL
#
- name: Setting ACLs
  ansible.builtin.include_tasks: set_acls.yml
  register: output

#
# Set users and AAA
#



#
# Set Interfaces
#

