---
# tasks file for cisco

#
# Include vars for the current site
#
- name: Include vars for the current switch
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "site_{{ site }}.yml"
        - "site_default.yml"

#
# Setting facts for Ciscos
#
- name: Setting Facts
  ansible.builtin.include_tasks: set_facts.yml
  register: output

#
# Setting global configuration
#
- name: Setting Global Configuration
  ansible.builtin.include_tasks: set_global_conf.yml
  register: output

#
# Setting vLANs
#
- name: Setting vLans
  ansible.builtin.include_tasks: set_vlans.yml
  register: output

#
# Setting STP
#
- name: Setting Spanning-Tree Protocol
  ansible.builtin.include_tasks: set_stp.yml
  register: output
