---
# tasks file for cisco

#
# Setting facts for Ciscos
#
- name: Setting Facts
  ansible.builtin.include_tasks: set_facts.yml
  register: output

#
# Setting global configuration
#
#- name: Setting Global Configuration
#  ansible.builtin.include_tasks: set_global_conf.yml
#  register: output

#
# Setting global configuration
#
- name: Setting vLans
  ansible.builtin.include_tasks: set_vlans.yml
  register: output
