---

#
# Setting the vLANs
#

- name: Creating vLANs dictionary
  set_fact:
    vlan_dict: "{{ vlan_dict | default([]) +
           [{ 'name' : item.name,
              'vlan_id' : item.id,
              'state' : item.active|default('active'),
              'shutdown' : item.shutdown|default('disabled') }
           ] }}"
  with_items: "{{ vlans_list }}"
  register: output

- name: Setting vLANs
  cisco.ios.ios_vlans:
    config:
      "{{ vlan_dict }}"
    state: overridden
  changed_when: false
  register: output

- name: Checking if vLANs changed
  set_fact:
    changed: "{{ output.before != output.after }}"
  changed_when: changed
  notify: SaveConfig
  register: output
