---

#
# Setting the ALCs
#

- name: Initializing variable
  set_fact:
    acls_dict: []
  when: acl_config is defined

- name: Creating ACLs dictionary
  include_tasks: inner_acls.yml
  with_items: "{{ acl_config }}"
  loop_control:
    loop_var: acl_item
  when: acl_config is defined

- name: Creating main dictionary
  set_fact:
    acls_config_dict: "{{ [{ 'afi' : 'ipv4',
                             'acls' : acls_dict }] }}"
  when: acl_config is defined

- name: Setting ACLs
  cisco.ios.ios_acls:
    config:
      "{{ acls_config_dict }}"
    state: overridden
  when: acl_config is defined
  notify: SaveConfig
  register: output

- name: Removing all ACLs config
  cisco.ios.ios_acls:
    config:
      - afi: ipv4
    state: deleted
  when: acl_config is undefined
  notify: SaveConfig
  register: output
