---

#
# Saving configuration
#
- name: Saving configuration
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Writing Running-Config
      cisco.ios.ios_command:
        commands: write memory
